version: '3.4'
services:
  mariadb:
    image: mysql:8.0
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: testt
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - ./mariadb:/var/lib/mysql
      - ./create_database.sql:/data/application/create_database.sql
      - ./create_tables.sql:/data/application/create_tables.sql
      - ./insert_data.sql:/data/application/insert_data.sql
      - ./create_triggers:/data/application/insert_data.sql



